name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: " 3.12.7"
      - name: Install dependencies
        run: |
          cd backend
          pip install -r requirements
          pip install pytest
      - name: Run tests
        run: |
          cd backend
          pytest

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version : "v20.18.0"
      - name: Install dependencies
        run: |
          cd frontend
          npm ci
      - name: Build
        run : |
          cd frontend
          npm run build